create extension if not exists pgcrypto;

create or replace function public.touch_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.members (
  member_id text primary key,
  first_name text not null check (char_length(trim(first_name)) > 0),
  last_name text not null check (char_length(trim(last_name)) > 0),
  full_name text not null check (char_length(trim(full_name)) > 0),
  instrument text not null check (char_length(trim(instrument)) > 0),
  is_active boolean not null default true,
  source_row_number integer,
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_members_touch_updated_at on public.members;
create trigger trg_members_touch_updated_at
before update on public.members
for each row
execute function public.touch_updated_at_column();

create table if not exists public.events (
  event_id text primary key,
  title text not null check (char_length(trim(title)) > 0),
  event_date date not null,
  source_column text,
  source_header text,
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_events_touch_updated_at on public.events;
create trigger trg_events_touch_updated_at
before update on public.events
for each row
execute function public.touch_updated_at_column();

create table if not exists public.attendance_entries (
  member_id text not null references public.members(member_id) on delete cascade,
  event_id text not null references public.events(event_id) on delete cascade,
  attendance_ratio numeric(5, 4) not null check (attendance_ratio >= 0 and attendance_ratio <= 1),
  source_raw_value text,
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (member_id, event_id)
);

drop trigger if exists trg_attendance_entries_touch_updated_at on public.attendance_entries;
create trigger trg_attendance_entries_touch_updated_at
before update on public.attendance_entries
for each row
execute function public.touch_updated_at_column();

create table if not exists public.sync_runs (
  id uuid primary key default gen_random_uuid(),
  pipeline_name text not null default 'sheet_to_supabase_sync',
  status text not null check (status in ('running', 'success', 'failed', 'dry_run')),
  dry_run boolean not null default true,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  source_kind text,
  source_ref text,
  summary jsonb not null default '{}'::jsonb,
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.sync_issues (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.sync_runs(id) on delete cascade,
  severity text not null default 'error' check (severity in ('warning', 'error')),
  code text not null,
  message text not null,
  row_number integer,
  column_ref text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.change_journal (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  actor text not null default 'system',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_sync_runs_started_at on public.sync_runs (started_at desc);
create index if not exists idx_sync_runs_pipeline_status on public.sync_runs (pipeline_name, status);
create index if not exists idx_sync_issues_run_id on public.sync_issues (run_id);
create index if not exists idx_change_journal_entity on public.change_journal (entity_type, entity_id, created_at desc);

alter table public.members enable row level security;
alter table public.events enable row level security;
alter table public.attendance_entries enable row level security;
alter table public.sync_runs enable row level security;
alter table public.sync_issues enable row level security;

drop policy if exists "Allow authenticated read members" on public.members;
create policy "Allow authenticated read members"
on public.members
for select
to authenticated
using (true);

drop policy if exists "Allow authenticated read events" on public.events;
create policy "Allow authenticated read events"
on public.events
for select
to authenticated
using (true);

drop policy if exists "Allow authenticated read attendance entries" on public.attendance_entries;
create policy "Allow authenticated read attendance entries"
on public.attendance_entries
for select
to authenticated
using (true);

drop policy if exists "Allow authenticated read sync runs" on public.sync_runs;
create policy "Allow authenticated read sync runs"
on public.sync_runs
for select
to authenticated
using (true);

drop policy if exists "Allow authenticated read sync issues" on public.sync_issues;
create policy "Allow authenticated read sync issues"
on public.sync_issues
for select
to authenticated
using (true);

grant select on public.members to authenticated;
grant select on public.events to authenticated;
grant select on public.attendance_entries to authenticated;
grant select on public.sync_runs to authenticated;
grant select on public.sync_issues to authenticated;
