alter table public.events
  add column if not exists source_sheet_id text,
  add column if not exists source_gid text;

create index if not exists idx_events_source_sheet_gid
  on public.events (source_sheet_id, source_gid, source_column);

create table if not exists public.sheet_member_rows (
  member_id text not null references public.members(member_id) on delete cascade,
  source_sheet_id text not null,
  source_gid text not null,
  source_row_number integer not null check (source_row_number > 0),
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (member_id, source_sheet_id, source_gid)
);

drop trigger if exists trg_sheet_member_rows_touch_updated_at on public.sheet_member_rows;
create trigger trg_sheet_member_rows_touch_updated_at
before update on public.sheet_member_rows
for each row
execute function public.touch_updated_at_column();

create table if not exists public.profile_member_links (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  member_id text not null references public.members(member_id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uniq_profile_member_links_member_id
  on public.profile_member_links (member_id);

drop trigger if exists trg_profile_member_links_touch_updated_at on public.profile_member_links;
create trigger trg_profile_member_links_touch_updated_at
before update on public.profile_member_links
for each row
execute function public.touch_updated_at_column();

create table if not exists public.attendance_change_queue (
  id bigint generated by default as identity primary key,
  status text not null default 'queued'
    check (status in ('queued', 'processing', 'applied', 'failed', 'dead_letter')),
  member_id text not null references public.members(member_id) on delete cascade,
  event_id text not null references public.events(event_id) on delete cascade,
  attendance_ratio numeric(5, 4) not null check (attendance_ratio >= 0 and attendance_ratio <= 1),
  requested_raw_value text,
  requested_by_profile_id uuid references public.profiles(id) on delete set null,
  requested_by_label text,
  request_note text,
  source text not null default 'app',
  source_sheet_id text,
  source_gid text,
  source_column text,
  source_row_number integer,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_error text,
  enqueued_at timestamptz not null default now(),
  claimed_at timestamptz,
  processed_at timestamptz,
  worker_run_id uuid references public.sync_runs(id) on delete set null,
  applied_cell_ref text
);

create index if not exists idx_attendance_change_queue_status_enqueued
  on public.attendance_change_queue (status, enqueued_at, id);

create unique index if not exists uniq_attendance_change_queue_open_pair
  on public.attendance_change_queue (member_id, event_id)
  where status in ('queued', 'processing');

create or replace function public.claim_attendance_change_queue_items(
  max_items integer default 25
)
returns setof public.attendance_change_queue
language plpgsql
security definer
set search_path = public
as $$
declare
  effective_limit integer;
begin
  effective_limit := least(greatest(coalesce(max_items, 25), 1), 200);

  return query
  with picked as (
    select q.id
    from public.attendance_change_queue q
    where q.status = 'queued'
    order by q.enqueued_at asc, q.id asc
    for update skip locked
    limit effective_limit
  )
  update public.attendance_change_queue q
     set status = 'processing',
         claimed_at = now(),
         attempt_count = q.attempt_count + 1
    from picked
   where q.id = picked.id
  returning q.*;
end;
$$;

comment on function public.claim_attendance_change_queue_items(integer)
  is 'Atomically claims queued attendance write jobs using FOR UPDATE SKIP LOCKED.';

create or replace function public.schedule_attendance_write_sheet_first_worker(
  function_url text,
  bearer_token text,
  cron_expression text default '*/1 * * * *',
  job_name text default 'attendance_write_sheet_first_worker_1m'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_job_id bigint;
  new_job_id bigint;
  command_sql text;
begin
  if function_url is null or char_length(trim(function_url)) = 0 then
    raise exception 'function_url is required';
  end if;

  if bearer_token is null or char_length(trim(bearer_token)) = 0 then
    raise exception 'bearer_token is required';
  end if;

  if to_regprocedure('cron.schedule(text,text,text)') is null then
    raise exception 'pg_cron is not enabled. Enable the extension before scheduling.';
  end if;

  if not exists (
    select 1
    from pg_proc
    join pg_namespace on pg_namespace.oid = pg_proc.pronamespace
    where pg_namespace.nspname = 'net'
      and pg_proc.proname = 'http_post'
  ) then
    raise exception 'pg_net is not enabled. Enable the extension before scheduling.';
  end if;

  for existing_job_id in
    select jobid
    from cron.job
    where jobname = schedule_attendance_write_sheet_first_worker.job_name
  loop
    perform cron.unschedule(existing_job_id);
  end loop;

  command_sql := format(
    $sql$
    select net.http_post(
      url := %L,
      headers := %L::jsonb,
      body := %L::jsonb,
      timeout_milliseconds := 300000
    );
    $sql$,
    function_url,
    jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || bearer_token
    )::text,
    jsonb_build_object(
      'trigger', 'cron',
      'mode', 'process'
    )::text
  );

  select cron.schedule(job_name, cron_expression, command_sql)
    into new_job_id;

  return new_job_id;
end;
$$;

comment on function public.schedule_attendance_write_sheet_first_worker(text, text, text, text)
  is 'Schedules queue worker Edge Function attendance_write_sheet_first.';

create or replace function public.unschedule_attendance_write_sheet_first_worker(
  job_name text default 'attendance_write_sheet_first_worker_1m'
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_job_id bigint;
  removed_count integer := 0;
begin
  if to_regprocedure('cron.unschedule(bigint)') is null then
    raise exception 'pg_cron is not enabled. Enable the extension before unscheduling.';
  end if;

  for existing_job_id in
    select jobid
    from cron.job
    where cron.job.jobname = unschedule_attendance_write_sheet_first_worker.job_name
  loop
    perform cron.unschedule(existing_job_id);
    removed_count := removed_count + 1;
  end loop;

  return removed_count;
end;
$$;

comment on function public.unschedule_attendance_write_sheet_first_worker(text)
  is 'Removes pg_cron jobs by name for attendance_write_sheet_first worker.';

alter table public.sheet_member_rows enable row level security;
alter table public.profile_member_links enable row level security;
alter table public.attendance_change_queue enable row level security;

drop policy if exists "Allow authenticated read own profile-member link" on public.profile_member_links;
create policy "Allow authenticated read own profile-member link"
on public.profile_member_links
for select
to authenticated
using (profile_id = auth.uid());

drop policy if exists "Allow authenticated read own queue rows" on public.attendance_change_queue;
create policy "Allow authenticated read own queue rows"
on public.attendance_change_queue
for select
to authenticated
using (requested_by_profile_id = auth.uid());

grant all on table public.sheet_member_rows to service_role;
grant all on table public.profile_member_links to service_role;
grant all on table public.attendance_change_queue to service_role;
grant usage, select on sequence public.attendance_change_queue_id_seq to service_role;

grant select on public.profile_member_links to authenticated;
grant select on public.attendance_change_queue to authenticated;

grant execute on function public.claim_attendance_change_queue_items(integer) to service_role;
grant execute on function public.schedule_attendance_write_sheet_first_worker(text, text, text, text) to service_role;
grant execute on function public.unschedule_attendance_write_sheet_first_worker(text) to service_role;
